// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/dict/v1/dict.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DictRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DictRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DictRequestMultiError, or
// nil if none found.
func (m *DictRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DictRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTag()) < 1 {
		err := DictRequestValidationError{
			field:  "Tag",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DictRequestMultiError(errors)
	}

	return nil
}

// DictRequestMultiError is an error wrapping multiple validation errors
// returned by DictRequest.ValidateAll() if the designated constraints aren't met.
type DictRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictRequestMultiError) AllErrors() []error { return m }

// DictRequestValidationError is the validation error returned by
// DictRequest.Validate if the designated constraints aren't met.
type DictRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictRequestValidationError) ErrorName() string { return "DictRequestValidationError" }

// Error satisfies the builtin error interface
func (e DictRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictRequestValidationError{}

// Validate checks the field values on DictResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DictResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DictResponseMultiError, or
// nil if none found.
func (m *DictResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DictResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Woker

	// no validation rules for Guide

	// no validation rules for Actor

	// no validation rules for Lawyer

	if len(errors) > 0 {
		return DictResponseMultiError(errors)
	}

	return nil
}

// DictResponseMultiError is an error wrapping multiple validation errors
// returned by DictResponse.ValidateAll() if the designated constraints aren't met.
type DictResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictResponseMultiError) AllErrors() []error { return m }

// DictResponseValidationError is the validation error returned by
// DictResponse.Validate if the designated constraints aren't met.
type DictResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictResponseValidationError) ErrorName() string { return "DictResponseValidationError" }

// Error satisfies the builtin error interface
func (e DictResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictResponseValidationError{}
