// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/xiaohubai/rpc-layout/app/dict/internal/biz"
	"github.com/xiaohubai/rpc-layout/app/dict/internal/conf"
	"github.com/xiaohubai/rpc-layout/app/dict/internal/data"
	"github.com/xiaohubai/rpc-layout/app/dict/internal/server"
	"github.com/xiaohubai/rpc-layout/app/dict/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dictRepo := data.NewDictRepo(dataData, logger)
	dictUsecase := biz.NewDictUsecase(dictRepo, logger)
	dictService := service.NewDictService(dictUsecase)
	httpServer := server.NewHTTPServer(confServer, dictService, logger)
	grpcServer := server.NewGRPCServer(confServer, dictService, logger)
	registrar := server.NewConsulRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
